spring.application.name=ms-ventas
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5433/db_ventas
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# URLs de microservicios dependientes
ms.clientes.url=http://localhost:8086
ms.productos.url=http://localhost:8082