spring.application.name=ms-ventas
server.port=8087

spring.datasource.url=jdbc:postgresql://postgres:5432/db_ventas
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# URLs de microservicios dependientes
ms.clientes.url=${MS_CLIENTES_URL:http://ms-clientes:8086}
ms.productos.url=${MS_PRODUCTOS_URL:http://ms-productos:8082}

logging.level.org.springframework.web=DEBUG